language: java
dist: trusty
sudo: false
install: true

git:
  depth: false

jdk:
  - oraclejdk8

script:
  - mvn clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "utarwyn-github"
