name: EnderContainers
author: Utarwyn
version: 2.0.1
main: fr.utarwyn.endercontainers.EnderContainers
softdepend: [Factions, PlotSquared, Citizens]
commands:
  endercontainers:
    aliases: [enderc, endc, enc, ecp]
    description: Main command of the EnderContainers plugin
    usage: "Usage: /endercontainers help"
  enderchest:
    aliases: [ec, enderc, enderch, echest, endchest]
    description: Allow you to open an enderchest anywhere
    usage: "Usage: /enderchest [number]"