name: EnderContainers
author: Utarwyn
version: 1.0.4
main: fr.utarwyn.endercontainers.EnderContainers
softdepend: [Factions, mcore]
commands:
  endercontainers:
    aliases: [ec]
    description: Allow you to create multiple ender containers
    usage: "Usage: /endercontainers help"
  enderchest:
    aliases: [enderc, enderch, endchest]
    description: Allow you to open an enderchest anywhere
    usage: "Usage: /enderchest [number]"