name: EnderContainers
author: Utarwyn
version: 1.0.6b
main: fr.utarwyn.endercontainers.EnderContainers
softdepend: [Factions, mcore, PlotSquared]
commands:
  endercontainers:
    aliases: [enderc, endc, enc, ecp]
    description: Allow you to create multiple ender containers
    usage: "Usage: /endercontainers help"
  enderchest:
    aliases: [ec, enderc, enderch, endchest]
    description: Allow you to open an enderchest anywhere
    usage: "Usage: /enderchest [number]"