name: Java Integration

on:
  push:
    branches: [ master, next ]
    paths:
      - 'api/**'
      - 'dependencies/**'
      - 'plugin/**'
      - '.github/workflows/**'
      - '*.gradle'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '16' ]
    name: Build with Java ${{ matrix.java }}
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build --stacktrace

      - name: Archive plugin jars on GitHub
        uses: actions/upload-artifact@master
        with:
          name: EssentialsX plugin jars
          path: jars/

  quality:
    runs-on: ubuntu-latest
    name: Check code quality
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore Gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Restore SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew :plugin:build :plugin:jacocoTestReport :plugin:sonarqube --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
