name: Java Integration

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Java JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.1
